### ISSUE TITLE
Proc macro support in rust-analyzer for nightly rustc versions

### ISSUE THREAD

**Issue by hedgehog1029** [fasterthanlime/feedback#101]
I found something wrong on this page:

  https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions#position=26.5

  Here's what it is:

Missing asset `assets/address-space.svg`? Or, it doesn't load for me:

![image](https://user-images.githubusercontent.com/3532945/191308841-c4939182-fc96-4e92-b7c2-61f5d468f0d3.png)

**Comment by fasterthanlime** [comment]
I'm assuming this was during a time where I had issues with my asset pipeline - this is what it should look like:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/7998310/224512322-fbfba482-43ad-473f-b012-b703149f107e.png">

Or in light theme:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/7998310/224512325-a80ec869-6d2b-49b8-828e-b7ff6dc4c6a9.png">

And that's how it looks to me right now, please re-open if it's still broken for you.
