### ISSUE TITLE
ELF relocations

### ISSUE THREAD

**Issue by yqmmm** [fasterthanlime/feedback#103]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-4#position=46.5

  Here's what it is:

In this code sample:
```rust
// converting `Option<T>` to `Result<T, E>` so we can use `?` to
// bubble up errors.
let addr = self.dynamic_entry(DT::Rela).ok_or(E::RelaNotFound)?;
let len = self.dynamic_entry(DT::RelaSz).ok_or(E::RelaSzNotFound)?;
let seg = self.segment_at(addr).ok_or(E::RelaSzNotFound)?;
```

I think the last error should be `E::RelaSegmentNotFound`?

**Comment by fasterthanlime** [comment]
You're absolutely correct, thanks.
