### ISSUE TITLE
Why is my Rust build so slow?

### ISSUE THREAD

**Issue by tomkarw** [fasterthanlime/feedback#105]
I found something wrong on this page:
https://fasterthanli.me/articles/why-is-my-rust-build-so-slow#position=23.4

Here's what it is:
```
And that's why cargo has a -Z timings option!
```

Nightly is no longer needed to use `timings`, would it make sense to update the article with a note?  
This is a message I get doing the "stable with nightly features hack":
```
$ cargo clean && RUSTC_BOOTSTRAP=1 cargo build --release --quiet -Z timings
warning: flag `-Z timings` has been stabilized in the 1.60 release, and is no longer necessary
  The -Ztimings option has been stabilized as --timings.
```

Big fan btw.

**Comment by fasterthanlime** [comment]
Fixed, thanks for the reminder (& the kind words!)
