### ISSUE TITLE
Metadata fields for posts not populated on import

### ISSUE THREAD

**Issue by yoshuawuyts** [fasterthanlime/feedback#106]
## Bug Description

When I import a post into Zotero, it doesn't know how to populate most of the metadata fields:

![Capture](https://user-images.githubusercontent.com/2467194/195346096-c788d94f-e839-487a-b445-1289bf2711db.PNG)

Other engines and tools which rely on metadata may experience similar issues; I just happened to run into this when importing this into my reference manager.

## Proposed Solution

You can fix this by adding the following metadata tags to your `<head>` section in the markup:

```html
<head>
    <meta name="author" content="firstname lastname">
    <meta property="article:published_time" content="yyy-mm-dd">
</head>
```

**Comment by fasterthanlime** [comment]
Pages now have this in `<head>`:

```html
<meta name="author" content="Amos Wenger">
<meta property="article:published_time" content="2022-02-11T07:30:00Z">
```

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7998310/224512110-25cbbfe3-52ff-4f0d-8f1a-f4677b47e063.png">


Better late than never 🤷
