### ISSUE TITLE
A Rust match made in hell

### ISSUE THREAD

**Issue by TmLev** [fasterthanlime/feedback#107]
I found something wrong on this page:

  https://fasterthanli.me/articles/a-rust-match-made-in-hell#position=11.8

Colors of `Protection::` variants don't match

<img width="591" alt="Screenshot 2022-10-18 at 21 58 19" src="https://user-images.githubusercontent.com/22966523/196519875-1d0a0812-4890-4940-81a4-27916c29e44e.png">

But they did a paragraph before:

<img width="411" alt="Screenshot 2022-10-18 at 21 59 10" src="https://user-images.githubusercontent.com/22966523/196520070-e159522d-16f9-44be-a9f4-9dd77597618d.png">

**Comment by fasterthanlime** [comment]
I'm not sure what happened there, but they seem to work now (I might've upgraded tree-sitter-highlight since):

<img width="878" alt="image" src="https://user-images.githubusercontent.com/7998310/224511964-cf8bb45f-1567-442f-8fbe-1b6bfe7f3490.png">
