### ISSUE TITLE
minor typo: the http crash course nobody asked for

### ISSUE THREAD

**Issue by lolPants** [fasterthanlime/feedback#109]
**Where's the problem at?**
https://fasterthanli.me/articles/the-http-crash-course-nobody-asked-for#making-http-2-requests-ourselves

**No, seriously, where is it?**
To avoid **_matchine_** on frame type several times, we'll rename our existing FrameType enum to RawFrameType

**Describe the issue and a fix if you know it**
"matchine" should be "matching".

**Comment by fasterthanlime** [comment]
Fixed, thanks!
