### ISSUE TITLE
The HTTP crash course nobody asked for

### ISSUE THREAD

**Issue by tjkirch** [fasterthanlime/feedback#114]
**Where's the problem at?**
https://fasterthanli.me/articles/the-http-crash-course-nobody-asked-for

**No, seriously, where is it?**
In the code just after "So, let's read those responses!" 

**Describe the issue and a fix if you know it**
This line is duplicated:
```
    let mut decoder = hpack::Decoder::new();
    let mut decoder = hpack::Decoder::new();
```

**Comment by fasterthanlime** [comment]
Fixed, thanks!
