### ISSUE TITLE
The HTTP crash course nobody asked for

### ISSUE THREAD

**Issue by tjkirch** [fasterthanlime/feedback#115]
**Where's the problem at?**
https://fasterthanli.me/articles/the-http-crash-course-nobody-asked-for

**No, seriously, where is it?**
In the shell session output just after "And.. let's try it out!"

**Describe the issue and a fix if you know it**
There are two sets of command output here, and I'm guessing you only intended the second one to be included.  The first shows a single response header, `:status: 200`, whereas the second command's output shows that plus many other headers.  You had just implemented the code to show headers and body, so showing a single header (without saying why) seemed slightly odd.  It also shows your full command prompt between the two sets of output, which doesn't appear anywhere else.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
