### ISSUE TITLE
My ideal Rust workflow "And the an unrelated PR" typo

### ISSUE THREAD

**Issue by jonathanbcarlson** [fasterthanlime/feedback#116]
**Where's the problem at?**
https://fasterthanli.me/articles/my-ideal-rust-workflow

**No, seriously, where is it?**
"And ~the~ an [unrelated PR against release-please](https://github.com/googleapis/release-please/pull/1095), all because of this article."

**Describe the issue and a fix if you know it**
It's grammatically incorrect. "And the an unrelated PR" should become "And an unrelated PR".

**Comment by fasterthanlime** [comment]
Fixed, thanks so much!
