### ISSUE TITLE
Reading files the hard way - Part 3

### ISSUE THREAD

**Issue by tjkirch** [fasterthanlime/feedback#117]
**Where's the problem at?**
https://fasterthanli.me/series/reading-files-the-hard-way/part-3

**No, seriously, where is it?**
Just before "Well, it's not much but - again, the values make sense."

**Describe the issue and a fix if you know it**
The code section just above this shows the creation of an `ExtentHeader` and printing it, and the text in the paragraph seems to reference the values in the output, but there's no image of the output.  You have to go down about a page to see an image that includes the extent header _and_ the extent, which was added afterward.  The HTML seems to show no evidence of an image present but failing to load, or anything like that.

**Comment by fasterthanlime** [comment]
I'm happy to report that, 4.5 months later, this has been fixed! In fact the whole series has been updated.
