### ISSUE TITLE
Dynamic linker speed and correctness

### ISSUE THREAD

**Issue by fatalerrorcoded** [fasterthanlime/feedback#118]
### Where's the problem at?
https://fasterthanli.me/series/making-our-own-executable-packer/part-8#position=79.4

### No, seriously, where is it?
That was easy! Lots of cloning, but Sym is relatively small, and the expected improvement in lookup time means it probably pays for itself. Or not.

**{% sc tip %} One really ought to make measurements before making claims like that.**

**And then not make the claims anyway, because measurements lie all the time. {% endsc %}**

Ok, what's next.. oh, Object::sym_name can go. Delete!

### Describe the issue and a fix if you know it
Instead of a hot tip block, the raw tags `{% sc tip %}` and `{% endsc %}` are displayed

**Comment by fasterthanlime** [comment]
I fixed that one when fixing another report - thanks nonetheless!
