### ISSUE TITLE
Remove development with Rust on fly.io "has goes from" and "to handled" typos

### ISSUE THREAD

**Issue by jonathanbcarlson** [fasterthanlime/feedback#119]
**Where's the problem at?**
https://fasterthanli.me/articles/remote-development-with-rust-on-fly-io

**No, seriously, where is it?**
"The client socket ~~has~~ goes from"
"it'll try to start a machine to ~~handled~~ the connection"

**Describe the issue and a fix if you know it**
They are grammatically incorrect.
- "socket has goes from" should become "socket goes from".
- "machine to handled the connection" should become "machine to handle the connection".

**Comment by fasterthanlime** [comment]
Clearly didn't have enough coffee when writing this one. Fixed, thanks!
