### ISSUE TITLE
Remote development with Rust on fly.io

### ISSUE THREAD

**Issue by nbw** [fasterthanlime/feedback#120]
# Summary

 `fly deploy` command looks for the docker file remotely by default.  Solution, use the `local-only` flag.

  https://fasterthanli.me/articles/remote-development-with-rust-on-fly-io#position=12.0

Your post:

```
 fly deploy
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'hello-axum' locally...
```

Reality:

```
hello-axum ~ fly deploy
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'hello-axum:latest' remotely...
Error failed to fetch an image or build from source: Authentication required to access image "docker.io/library/hello-axum:latest"
```

I did some [perusing of the CLI](https://github.dev/superfly/flyctl/blob/1d88f5128538312c7b6d34e2437e17ed05fc1042/internal/flag/flag.go#L253) and realized there's a local-only flag.

This works:

```
hello-axum ~ fly deploy --local-only
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'hello-axum:latest' locally...
....
```

--     

Saw your tweet about leaving Fly and doing your own thing. Good luck! Please keep putting out great content.

**Comment by fasterthanlime** [comment]
You're absolutely correct, flyctl changed its default behavior at some point, to my great chagrin.

I added the flag to this article.

> Saw your tweet about leaving Fly and doing your own thing. Good luck! Please keep putting out great content.

🥰
