### ISSUE TITLE
[Rust modules vs files] it should recommend 2021 edition instead of the 2018 one

### ISSUE THREAD

**Issue by dbofmmbt** [fasterthanlime/feedback#121]
**Where's the problem at?**

On the ["important note" section of the modules article](https://fasterthanli.me/articles/rust-modules-vs-files#important-note) and also in the `Cargo.toml` snippet from the ["crates dependencies" section](https://fasterthanli.me/articles/rust-modules-vs-files#crate-dependencies).

**No, seriously, where is it?**

On the last paragraphs of the important note:
```
If you have an existing project, you can check that you're using the 2018 edition by looking for an edition = 2018 line in the [package] section. If you don't have one - add it now.

If you make a new project with cargo new / cargo init and the latest Rust, it'll automatically select 2018 edition for you.
```

And on the `Cargo.toml` in the section after it:
![Cargo.toml with `edition = "2018"`](https://user-images.githubusercontent.com/34381457/200367203-e58caab8-5d45-4070-ac94-95fa8266baff.png)

**Describe the issue and a fix if you know it**

This note rightfully explains that the 2015 edition won't be explained and instructs users to use the 2018 edition. But today we have the 2021 edition, so beginners should be using it instead of the 2018 one.

**Comment by fasterthanlime** [comment]
You're absolutely correct - fixed.
