### ISSUE TITLE
GDB scripting and Indirect functions

### ISSUE THREAD

**Issue by ETKNeil** [fasterthanlime/feedback#122]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-9#position=32.9

  Here's what it is:
```rust
/// parses a Linux device number in form major:minor, where
/// major and minor are decimal numbers
fn dev(i: &str) -> IResult<&str, Dev> {
    let (i, (major, minor)) = separated_pair(dec_number, tag(":"), dec_number)(i)?;
    Ok((i, Dev { major, minor }))
}
```

This is an incorrect assumption Dev numbers are actually hex numbers, to give you an idea on fedora you usually encounter fd:01 which is the mappings 253:1 for vda2 see https://unix.stackexchange.com/questions/305568/how-to-find-device-whose-major-id-is-fd

In general we expect people to read elfutils code which I have to say is pretty bad : https://chromium.googlesource.com/external/elfutils/+/refs/heads/master/libdwfl/linux-proc-maps.c#220 (see %x:%x)

Tbh the man do not mention this particularity : https://man7.org/linux/man-pages/man5/proc.5.html (seach for `dev is the device (major:minor);` )

**Comment by fasterthanlime** [comment]
Thanks for the heads up! I've adjusted the code to parse those as hex.
