### ISSUE TITLE
Request coalescing in async Rust

### ISSUE THREAD

**Issue by tjkirch** [fasterthanlime/feedback#124]
**Where's the problem at?**
https://fasterthanli.me/articles/request-coalescing-in-async-rust

**No, seriously, where is it?**
After setting up Jaeger, just after this sentence: `And notice that the attributes we've set are there: they're called "tags" here.`

**Describe the issue and a fix if you know it**
It says `accept_connection has the addr` but I believe it should say `handle_connection` rather than `accept_connection`, since "accept_connection" isn't a thing in the article, and "handle_connection" in the picture _does_ show the "addr" tag.

**Comment by fasterthanlime** [comment]
Nice catch, thanks!
