### ISSUE TITLE
Missing includes in "Reading files the hard way - Part 2 (x86 asm, linux kernel)"

### ISSUE THREAD

**Issue by EvacuateJuly** [fasterthanlime/feedback#127]
https://fasterthanli.me/series/reading-files-the-hard-way/part-2#position=22.1
Includes seem to be missing from this listing.
```
int main(int argc, char **argv) {
    int fd = open("/etc/hosts", O_RDONLY);

    printf("Our file descriptor for /etc/hosts is %d\n", fd);
    printf("Press enter to exit...\n");
    getc(stdin);
}
```

**Comment by fasterthanlime** [comment]
I've recently gone over the whole series again and noticed that too - the includes are.. included, now.

Thanks for the report!
