### ISSUE TITLE
Cleaning up and upgrading third-party crates

### ISSUE THREAD

**Issue by AlyssaRoseDev** [fasterthanlime/feedback#128]
I found something wrong on this page:

  https://fasterthanli.me/series/updating-fasterthanli-me-for-2022/part-1#position=24.0

  Here's what it is:
"Here it's not just about making code simpler (although it is one less call, so, less work for the compiler), it's also about performance: the later form lets the compiler [create the value directly on the heap](https://nnethercote.github.io/perf-book/standard-library-types.html#box)." seems like it should say "the latter form" instead of "the later form"

**Comment by fasterthanlime** [comment]
Fixed, thanks!
