### ISSUE TITLE
Migrating from warp to axum

### ISSUE THREAD

**Issue by Angr1st** [fasterthanlime/feedback#131]
I found something wrong on this page:

  https://fasterthanli.me/series/updating-fasterthanli-me-for-2022/part-2#position=55.7

  Here's what it is:

> It let you specify which state type you're using in that application

I think it should be "It let's you specify which state type you're using in that application"

p.s. I also sent you an email about it.

**Comment by fasterthanlime** [comment]
I think I fixed that one when I got the e-mail :)
