### ISSUE TITLE
/login buttons overflow vertically on mobile

### ISSUE THREAD

**Issue by peter50216** [fasterthanlime/feedback#132]
I found something wrong on this page:

  https://fasterthanli.me/login?return_to=#position=0.0

  Here's what it is:
On mobile, the login buttons text is out of bound of the button itself and doesn't look good.
(likely broken by the new login via GitHub button)
![Screenshot_20221127-022155](https://user-images.githubusercontent.com/891109/204103559-05a9baf0-d9e3-4a8e-8837-d130a71db152.png)

**Comment by fasterthanlime** [comment]
fixed!

desktop:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/7998310/224511429-dc7bf72d-8112-427b-97fe-f87f07d0cc48.png">

mobile:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/7998310/224511433-e1d74439-9981-4d7d-8b1a-38c78f5d67ae.png">

thanks for the report.
