### ISSUE TITLE
Small strings in Rust

### ISSUE THREAD

**Issue by Millione** [fasterthanlime/feedback#133]
I found something wrong on this page:

  https://fasterthanli.me/articles/small-strings-in-rust#position=87.8

  Here's what it is:

> That's not surprising, as smol uses Arc\<String\> for those - which also means it's Send and Sync.

It seems like smol uses Arc\<str\>
Ref: https://github.com/rust-analyzer/smol_str/blob/d6b8d67003969022ab2c9e7cd61560495bd14833/src/lib.rs#L337

**Comment by fasterthanlime** [comment]
nice catch, thank you!
