### ISSUE TITLE
Using GraphQL variables in "Log in with GitHub"

### ISSUE THREAD

**Issue by yanns** [fasterthanlime/feedback#134]
I found a possible improvement on this page:

  https://fasterthanli.me/series/updating-fasterthanli-me-for-2022/part-6#position=0.0

  Here's what it is:

For the GraphQL query, instead of using `user(login: ${LOGIN})`and `replace`, you could use a variable and send the value in the `variables`. [Ex](https://docs.commercetools.com/api/graphql#query-graphql)

GitHub's GraphQL endpoint supports that too! [https://docs.github.com/en/graphql/gui](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#working-with-variables)

This avoids GraphQL injection security issues...
(And it makes also possible to save the query in another file and use some tools that can be validate all queries against the schema.)

**Comment by fasterthanlime** [comment]
Not only did I update the article, I also updated my website to use variables x)

Thanks!
