### ISSUE TITLE
fasterthanli.me

### ISSUE THREAD

**Issue by CAD97** [fasterthanlime/feedback#135]
I found something wrong on this page:

  https://fasterthanli.me/#position=0.0

  Here's what it is:

The homepage "I owe a debt of gratitude to every one of my patrons," links to your Patreon page and gives no credit to the GitHub Sponsors (which IIRC you've expressed a preference for new donors to use?).

There are two obvious improvements that could be made:

- simple: reword to "my [patrons](https://www.patreon.com/fasterthanlime) and [sponsors](https://github.com/sponsors/fasterthanlime#sponsors)" and link "sponsors" to the GitHub Sponsors page
- involved: add a thanks page to the website which aggregates and links to both places to support your work

The latter becomes more beneficial if you introduce another way to support you directly.

**Comment by fasterthanlime** [comment]
Good catch! I'll need to address that.

**Comment by fasterthanlime** [comment]
I've changed the wording since!
