### ISSUE TITLE
AoC Day 5 unnecessary complexity 

### ISSUE THREAD

**Issue by salameme** [fasterthanlime/feedback#137]
**Where's the problem at?**
https://fasterthanli.me/series/advent-of-code-2022/part-5

**No, seriously, where is it?**
```rust
fn parse_number(i: &str) -> IResult<&str, usize> {
    map_res(take_while1(|c: char| c.is_ascii_digit()), |s: &str| {
        s.parse::<usize>()
    })(i)
}
```

**Describe the issue and a fix if you know it**
Nom has `digit1` to replace `take_while1(is_digit)`

The code can therefore be replaced with:
```rust
fn parse_number(i: &str) -> IResult<&str, usize> {
    map_res(digit1, |s: &str| {
        parse::<usize>()
    })(i)
}
```

Or also (this avoids creating a closure, I know it works, but you might be able to replace it with str::parse and have it infer the return type, I sadly can't test it):
```rust
fn parse_number(i: &str) -> IResult<&str, usize> {
    use std::Str::FromStr;
    map_res(digit1, usize::from_str)(i)
}
```

**Comment by fasterthanlime** [comment]
I've added a section with this - it's not deployed yet, but it will be soon!
