### ISSUE TITLE
Small typo in Advent of Code Day 7

### ISSUE THREAD

**Issue by 8bitbanana** [fasterthanlime/feedback#139]
**Where's the problem at?**
Just a small typo in https://fasterthanli.me/series/advent-of-code-2022/part-7

**No, seriously, where is it?**

> Most of the errors boild won to "cannot borrow X as mutable more than once at a time". And that's... the crust of Rust. You can only ever have one mutable reference to something at a time. Anything else is insta-UB. And that rules keeps us safe.

"Most of the errors **boild won**"

**Describe the issue and a fix if you know it**
I believe it should be **boil down**?

Great article as always, been loving the advent of code series!

**Comment by fasterthanlime** [comment]
Fixed, thanks! I guess my cat jumped on me as I typed this 🥲
