### ISSUE TITLE
Missing rust snippet

### ISSUE THREAD

**Issue by DusterTheFirst** [fasterthanlime/feedback#142]
**Where's the problem at?**
https://fasterthanli.me/series/advent-of-code-2022/part-9

**No, seriously, where is it?**
The constructor becomes this:

[empty Rust code block]

And update_state, this:

**Describe the issue and a fix if you know it**
The rust code block between these two paragraphs is empty.

**Comment by fasterthanlime** [comment]
Thanks! It was indeed missing, I've just fixed it.
