### ISSUE TITLE
Example file tree showing shared parents indented wrong

### ISSUE THREAD

**Issue by zanedp** [fasterthanlime/feedback#143]
**Where's the problem at?**
[Advent of Code Day 7, Rc/RefCell](https://fasterthanli.me/series/advent-of-code-2022/part-7#using-rc-refcell).

**No, seriously, where is it?**
In the example file tree trying to explain shared parent relationships:
![image](https://user-images.githubusercontent.com/295055/207405833-01583cb8-916e-4a68-892e-a6bc7f30b0ad.png)

**Describe the issue and a fix if you know it**
`c` should be indented to the same level as `b`. As is, `c`'s parent is `b` not `a` as intended.

**Comment by fasterthanlime** [comment]
Very nice catch, thank you.

You know how that happened? When I create a new markdown file, VSCode defaults to "indenting with tabs". I typed that tree manually: `- a`, newline, `space space - b`, enter `- c` (and VSCode inserts a tab to align `-c` with the previous line).

Then after I copy/paste a few bits of sample code, I notice that it's set wrong, run "Detect indentation from content", and "Convert indentation to spaces" and at that point, somehow, tabs are converted to 4 spaces and everything is off.

Anyway I've fixed my editor settings so this shouldn't happen again.
