### ISSUE TITLE
Advent of code wasm embeds not fully visible

### ISSUE THREAD

**Issue by DusterTheFirst** [fasterthanlime/feedback#145]
**Where's the problem at?**
Advent of code day 10 and day 9

**No, seriously, where is it?**
The wasm demos in both articles. 

**Describe the issue and a fix if you know it**
When on a small width display (phone, iOS) the wasm demos get cut off at the sides. There is a scroll bar at the bottom for horizontal scrolling, but it is not possible to scroll the full width of the demo. This hides very important content like the start button. 

https://user-images.githubusercontent.com/14093962/207582352-d23c4b6e-bef8-4d8a-9f43-c773b0aadc5d.MOV

(You can ignore the weird white background artifacts, they do not show up in safari. They look like a renderer problem in iOS Firefox)

**Comment by fasterthanlime** [comment]
I noticed that too on my Android phone, even though I tried to make that solution semi-responsive (the "display"'s font size changes for small displays). It's unlikely I'll have time to fix it in the near future - I wonder if it's possible to open the iframe's source from a mobile browser?

**Comment by DusterTheFirst** [comment]
It might make sense, as a stand in, to include a link to the iframe source directly next to the iframe for mobile or otherwise.

**Comment by fasterthanlime** [comment]
I made the font smaller on smaller screens, hopefully it should fit now!
