### ISSUE TITLE
Day 12 (Advent of Code 2022)

### ISSUE THREAD

**Issue by tjkirch** [fasterthanlime/feedback#146]
**Where's the problem at?**
https://fasterthanli.me/series/advent-of-code-2022/part-12#finding-walkable-neighbors - yay anchors!

**No, seriously, where is it?**
`It also tells us the start cell has the lowest elevation, and the highest cell has the highest elevation.`

**Describe the issue and a fix if you know it**
"the highest cell has the highest elevation" is sort of a tautology, and I'm guessing it should say "the **end** cell has the highest elevation"

**Comment by fasterthanlime** [comment]
Nice find, thanks! Yay anchors indeed.
