### ISSUE TITLE
Day 13 (Advent of Code 2022)

### ISSUE THREAD

**Issue by korrat** [fasterthanlime/feedback#147]
I have two suggestions regarding your solution to [AoC 2022 Part 13](https://fasterthanli.me/series/advent-of-code-2022/part-13#position=74.9).

1. Since Node implements `Ord`, you can use the `Ord` implementation on slices for lexicographic ordering.
2. For the second part, you don't have to sort the packets, you can instead count the packets below each divider packet, reducing runtime from O(n * log n) to O(n).

**Comment by fasterthanlime** [comment]
I've integrated both suggestions, thanks!
