### ISSUE TITLE
Day 1 (Advent of Code 2022)

### ISSUE THREAD

**Issue by Hodkinson** [fasterthanlime/feedback#149]
I found something wrong on this page:

  https://fasterthanli.me/series/advent-of-code-2022/part-1#position=96.0

  Here's what it is:
The line in the final solution:

`.batching(|mut it| (&mut it).map_while(|x| x).sum1::<u64>())`

I'm not sure that the extra `mut` sprinkling is needed, for me this works fine.

`.batching(|it| it.map_while(|x| x).sum1::<u64>())`

Apologies if I've missed something that's happening for performance/other reasons, I saw the comment before about not consuming the iterator but I can't see how it applies in this case.

**Comment by fasterthanlime** [comment]
Thanks!
