### ISSUE TITLE
Dynamic linker speed and correctness

### ISSUE THREAD

**Issue by nortti0** [fasterthanlime/feedback#15]
I found something wrong on this page:

https://fasterthanli.me/series/making-our-own-executable-packer/part-8#position=86.7

Here's what it is:

> Now, we can map our Vec<Sym> to a `Vec``:

I presume the backticks are meant to get code formatting, but the extra one prevented that from being triggered.

> {% sc tip %} One really ought to make measurements before making claims like that.
> And then not make the claims anyway, because measurements lie all the time. {% endsc %}

The "{% sc tip %}" / "{% endsc %}" seem like section directives that got passed to the final product for some reason.

> we simply use 0x0 as its address instead of whatever it would've been if it was *designed* by one of the other ELF objects.

I'm not sure if the word "designed" here is just something I am unfamiliar with, or if it is a proofreading mistake.

**Comment by fasterthanlime** [comment]
Fixed earlier today, here's what it was _supposed_ to say:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/7998310/224513816-388464ec-64b4-419e-99bc-0a42eb349036.png">

The tip also is fixed:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/7998310/224513820-8d940d48-8f07-4c74-ab74-dcb83e0bd47e.png">




> I'm not sure if the word "designed" here is just something I am unfamiliar with, or if it is a proofreading mistake.

I think I meant "defined" - fixed it to that.
