### ISSUE TITLE
Some formatting issues

### ISSUE THREAD

**Issue by komu** [fasterthanlime/feedback#150]
**Where's the problem at?**

https://fasterthanli.me/series/making-our-own-executable-packer/part-8

**No, seriously, where is it?**

First:

>  _Now, we can map our Vec\<Sym\> to a Vec_.

Second:

> {% sc tip %} One really ought to make measurements before making claims like that.
> 
> And then not make the claims anyway, because measurements lie all the time. {% endsc %}

**Describe the issue and a fix if you know it**

For the first case it seems like there's an extra backtick that breaks the formatting.

For the second case, I'm not seeing the cool bear 😢, but just some markup.

Thanks for an awesome series!

**Comment by fasterthanlime** [comment]
Fixed, thanks!
