### ISSUE TITLE
better to support chrome translation

### ISSUE THREAD

**Issue by takkuumi** [fasterthanlime/feedback#152]
thx your blog, it's a very nice blog.

but, it's not friendly for browser translation. if i use chrome translation, it's like this:

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/9606668/210920306-a6c1763f-da76-4514-bb31-7eef006f878e.png">

I think it's better show translation like this

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/9606668/210920577-dedfba57-440b-4d6c-83e5-118dc7fcca28.png">

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/9606668/210920517-993fcbcd-336b-4d57-a680-00879db231a9.png">
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/9606668/210920593-d0548d89-caba-407a-a3e5-1e13c9655f24.png">

**Comment by fasterthanlime** [comment]
This might work: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate

**Comment by takkuumi** [comment]
@fasterthanlime if  put the text with `pre` and `code` htmlelement, it will not translate by the  browsers.

```html
<pre>
    <code>
        <span>a<i>b</i>c</span>
        <strong>....</strong>
        <!-- and so on -->
     </code>
</pre>

```

**Comment by fasterthanlime** [comment]
> if put the text with `pre` and `code` htmlelement, it will not translate by the browsers.

yeah, it used to be that way, but that breaks TUI browsers like lynx: https://github.com/fasterthanlime/feedback/issues/4

I've added `translate=no` to all code blocks: 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/7998310/211168319-6aba2966-f9d9-49d2-bc47-1041ed5889f6.png">
