### ISSUE TITLE
either will or either with?

### ISSUE THREAD

**Issue by RustyStriker** [fasterthanlime/feedback#153]
**Where's the problem at?**
https://fasterthanli.me/articles/twitch-fell-behind

**No, seriously, where is it?**
I have ~850 followers on Twitch right now, and sometimes, even though I tell folks not to, someone will subscribe to the channel, either *will* real money or the one free subscription they get through Amazon Prime (since Twitch is an Amazon company now, [in case you missed the memo](https://www.businessinsider.com/amazon-buys-twitch-2014-8)).
(5th paragraph in the `Lets talk numbers` section)

**Describe the issue and a fix if you know it**
Marked in bold, second line you wrote either will where i suspect you meant either *with*

**Comment by fasterthanlime** [comment]
Thanks!
