### ISSUE TITLE
Sun/moon switcher looks like a logo that goes to the front page

### ISSUE THREAD

**Issue by philfiru** [fasterthanlime/feedback#155]
I found something ~~wrong~~ unusual on this page:

  https://fasterthanli.me/#position=17.8

  Here's what it is:
I thought the button in the upper left was a logo that I could click on to get to the front page, only to be flashed.

**Comment by fasterthanlime** [comment]
I agree that "link to home" should be top-left-most, so I've moved the moon/sun switcher next to search instead.
