### ISSUE TITLE
Day 2 (Advent of Code 2022)

### ISSUE THREAD

**Issue by mountainjoe** [fasterthanlime/feedback#157]
I found something wrong on this page: your `expect` strings for winning move and losing are the same and they should probably be different.

  https://fasterthanli.me/series/advent-of-code-2022/part-2#position=89.7

  Here's what it is:

    fn winning_move(self) -> Self {
         ...
            .expect("at least one move beats us") <-- we win with at least one move? one move exists where we win?
    }

    fn losing_move(self) -> Self {
        ...
            .expect("at least one move beats us") <--
    }

**Comment by fasterthanlime** [comment]
Thanks!
