### ISSUE TITLE
Cargo Add now built in, Making Our Own Ping: Part 6.

### ISSUE THREAD

**Issue by Dygear** [fasterthanlime/feedback#158]
**Where's the problem at?**
[Making Our Own Ping: Part 6](https://fasterthanli.me/series/making-our-own-ping/part-6)

**No, seriously, where is it?**
> Cool bear's hot tip:
> Reminder: `cargo add` is provided by [cargo-edit](https://crates.io/crates/cargo-edit).

**Describe the issue and a fix if you know it**
You can delete this as it's been built in for a little while. (Since Rust 1.62.0)

**Comment by fasterthanlime** [comment]
thanks!
