### ISSUE TITLE
Finding the default network interface through WMI: More Information

### ISSUE THREAD

**Issue by Dygear** [fasterthanlime/feedback#159]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-ping/part-7#position=6.0

  Here's what it is:
> Why do raw sockets require administrative privileges? Presumably because having access to raw sockets allows you to do all sorts of fun things, like IP spoofing - pretending you're another host on the network.

So there is a pretty long reason behind this, but it was massively helped by Steve Gibson, of grc.com (Gibson Research Corporation.) The links below show where it was talked about from all over the spectrum. Steve gave a few interviews on TechTV [RIP], MSNBC, and the likes. I could not find any of these videos unfortunately. But After Windows XP came out with raw sockets, it was removed from user land and placed behind a Admin wall because of people like Steve Gibson saying it was far to dangerous and XP would turn into a zombie paradise.

[1]: http://www.interact-sw.co.uk/iangblog/2004/08/12/norawsockets
[2]: https://www.informit.com/articles/article.aspx?p=27289
[3]: https://arstechnica.com/information-technology/2014/04/memory-lane-before-everyone-loved-windows-xp-they-hated-it/

**Comment by fasterthanlime** [comment]
I've linked to here from there, do come back and post videos if you find them!
