### ISSUE TITLE
Binding C APIs with variable-length structs and UTF-16

### ISSUE THREAD

**Issue by Dygear** [fasterthanlime/feedback#160]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-ping/part-8#position=84.1

  Here's what it is:
> Mhhh we can, but then we can't derive Debug anymore. Why are std traits only implemented for arrays of size up to 32? Because Rust (as of 1.38) doesn't have dependent types. Will it ever get them? [Steve has the answer](https://news.ycombinator.com/item?id=19675611).

It's no so much wrong, but maybe worth an update. It looks like for the most part these died in the womb. All of the PR were closed without merging.

**Comment by fasterthanlime** [comment]
Well, it seems in Rust 1.68.0 you _can_ derive Debug on that!

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=15777a2d8fafbefcef9439374ca22cb2

I've updated the text.
