### ISSUE TITLE
Code blocks can be wider than the text, which can look a bit jarring

### ISSUE THREAD

**Issue by deepbluev7** [fasterthanlime/feedback#162]
**Where's the problem at?**
https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer

(But it probably affects all of them)

**No, seriously, where is it?**
Copy/paste the paragraph the problem is in, maybe highlight what's wrong?

![image](https://user-images.githubusercontent.com/16312324/218516294-efb2d709-92c6-4e54-a439-e19e2b4888b2.png)

**Describe the issue and a fix if you know it**
I would usually expect code blocks to be similar to the text around it. But on my screen (which might be a bit wide, 2560px across without any scaling),  articles might look like this:

![image](https://user-images.githubusercontent.com/16312324/218516792-16674711-f166-461a-99ac-97a759900728.png)

It seems to jump to a wider size at about 1200px width.

That seems to come from the following rule:

![image](https://user-images.githubusercontent.com/16312324/218520446-e4419837-9dbf-48c3-8646-1b2fea6ace44.png)

While the paragraphs seem to use this rule:

![image](https://user-images.githubusercontent.com/16312324/218520933-faabee0e-9ed8-434a-9214-59a449f98837.png)

Maybe a 760px max width makes sense there too (or just dropping that extra rule). I can understand why some people might want to make their window wider to see the full code without scrolling, so maybe this is a bad idea, I just noticed that the wide blocks looked a bit out of place. (The same applies probably also to images.) Also the extra rule suggests, that this was done intentionally, although it might have been for a different reason and shouldn't have applied here.

Feel free to close this, if it is intentional. I have no idea about design and stuff! Thank you for the enjoyable content as always!

**Comment by fasterthanlime** [comment]
This is indeed intentional, some code gets quite wide and is read differently from prose, which benefits from narrower columns.

I'm sure this annoys other people too, but right now I feel like it's the least bad compromise, even though it does look funny when there's short/narrow shell sessions.
