### ISSUE TITLE
The bottom emoji breaks rust-analyzer

### ISSUE THREAD

**Issue by GoldsteinE** [fasterthanlime/feedback#163]
I found something wrong on this page:

  https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer#position=95.4

  Here's what it is:

> "Sending the correct UTF-16 code unit offsets" would probably involve something like re-encoding lines from "whatever Emacs uses internally" (presumably UTF-8) to UTF-16, which can be time-consuming, especially if you're doing that in Common Lisp I suppose. Or you could do something smarter, like rust-analyzer does, but then you better have good unit tests (like rust-analyzer also does).

`s/Common Lisp/Emacs Lisp/`, which is a distinct language

**Comment by fasterthanlime** [comment]
Thanks, I've fixed the article.
