### ISSUE TITLE
Typo in "The bottom emoji breaks rust-analyzer"

### ISSUE THREAD

**Issue by gennyble** [fasterthanlime/feedback#165]
**Where's the problem at?**
12th paragraph *(not counting code blocks; are code blocks paragraphs?)* of [The bottom emoji breaks rust-analyzer: Reproducing the issue, part 1 ](https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer#reproducing-the-issue-part-1)

**No, seriously, where is it?**
Emphasis mine (words, yours):
> Opening the `src/main.rs` ***against*** prompts me to import a workspace root, I pick the first option, which seems reasonable, and tada, we have Rust highlighting and inline documentation and stuff!

**Describe the issue and a fix if you know it**
Is that supposed to be "Opening the `src/main.rs` again"?

**Comment by fasterthanlime** [comment]
Fixed, thanks 💛
