### ISSUE TITLE
Bottom emoji in inverted color (dark theme) is the stuff of nightmares

### ISSUE THREAD

**Issue by mothdotmonster** [fasterthanlime/feedback#167]
inverting images looks bad when those images have color.

example: 
![image](https://user-images.githubusercontent.com/82258270/218599076-28365c5f-d478-49ba-8742-8ce809bc14a4.png)

perhaps you can solve this by having a prerendered light and dark version?

**Comment by fasterthanlime** [comment]
Yeah I noticed that too :/ can't be bothered to fix it right now, but it does look bad. Emojis actually don't work at all with my draw.io => printable SVG pipeline (something somewhere breaks) so this is a PNG embedded in there, I thought there might be some CSS trickery to do, but.. not with `<img src="some.svg">`.

I'll try to think of a more scalable issue than exporting everything twice.

**Comment by fasterthanlime** [comment]
I've "solved" the problem by removing the emoji from that diagram for now.
