### ISSUE TITLE
A no_std Rust binary

### ISSUE THREAD

**Issue by dlazerka** [fasterthanlime/feedback#17]
I found something wrong on this page:

https://fasterthanli.me/series/making-our-own-executable-packer/part-12#position=33.8

Here's what it is:

Thanks for nice tutorial!

Seems that it doesn't work, probably Rust got changed. (Caution, I'm Rust newbie)
Updates to make:

1. Instead of `!` return type you need `()`.
2. Remove `#![feature(asm)] `.
3. Add `use core::arch::asm;` to use `asm!` macro.
4. In build.rs you need `println!("cargo:rustc-link-arg=-nostartfiles");`.

rustc 1.60.0

**Comment by fasterthanlime** [comment]
I fixed 4 earlier today, and I just fixed 2 and 3, but I'm skeptical of 1: it might be that the Rust compiler refuses to compile like that but.. it truly never does return, so.. ?
