### ISSUE TITLE
A typo in Part 7 of the Nix series

### ISSUE THREAD

**Issue by lyssieth** [fasterthanlime/feedback#174]
**Where's the problem at?**
[The article](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-7#:~:text=from%20start%20to%20finish%20it%20and%20I%20trust%20it%20somewhat)

Using the fancy url link highlight feature, don't know if it works in your browser. Specifically, the issue is highlighted in bold in this quote block:
> This is because, you need to tell docker build to share your SSH credentials. Otherwise any Dockerfile could just steal them. I still think the security model is kinda wonky there, but, we've written our own Dockerfile from start to finish **it** and I trust it somewhat.

**Describe the issue and a fix if you know it**
I'm pretty sure you just remove the `it` from where it's bolded and you'll be fine. Probably.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
