### ISSUE TITLE
tracing and otel

### ISSUE THREAD

**Issue by zoranzaric** [fasterthanlime/feedback#179]
Hi and thanks a lot for your superb content!  I hope stating interest in topics you scratch is fine via your feedback process!  If not I'm sorry to bother you and would love to hear how to do this in a more appropriate way.

Anyways… in Part 4 of your nix series you write:

> There's two main reasons: the first, is that I don't like tying tracing and opentelemetry. I've had bad experiences in the past trying to dynamically filter the "tracing" end of things to make sure opentelemetry receives what I want.
>
> (There's options, I just ran into trouble. It's a long story.)

I would very much love to hear the long story.
At $work I'm buying heavily into tracing and otel, so info on this would be great.

Thanks again for your amazing work, I hope you are doing fine and I look forward hearing back from you.

Best regards from Germany,
Zoran

**Comment by fasterthanlime** [comment]
The long story is something I'm unfortunately not able to prove, but essentially - the `tracing` crate performs some optimizations based on the assumption that certain callsites, if filtered-out when first entered, will remain filtered-out. If you dynamically change filtering, that doesn't hold any more.

There's other assumptions also related to callsites that break when you hold onto spans around and do things with them later. The short of it is that I broke some tracing invariants I didn't know existed, and nothing seemed to work like I wanted.

Overall I've found "dynamic filtering with tracing" to be really hard to achieve, in a way that isn't with the (much more expensive, but also much more dynamic in nature) otel crates.

The details are lost to some proprietary git repository I no longer have access to, sorry.
