### ISSUE TITLE
Thread-local storage

### ISSUE THREAD

**Issue by nortti0** [fasterthanlime/feedback#18]
I found something wrong on this page:

https://fasterthanli.me/series/making-our-own-executable-packer/part-13#position=25.9

Here's what it is:

> & \space &0011 \space &0100 \space &1010 \space &1001 \space &\text{Offset} \space &\text{(16 bits)} \ \hline \ &0110 \space &1011 \space &1101 \space &0001 \space &1001 \space &\text{Address} \space &\text{(20 bits)} \ \end{aligned} +​0110  0110 ​1000 0011 1011 ​1000 0100 1101 ​0111 1010 0001 ​ 1001 1001 ​Segment Offset Address ​(16 bits) (shifted left by 4)(16 bits)(20 bits)​​

This seems like formatting directives that got through the rendering pipeline.

**Comment by fasterthanlime** [comment]
Fixed! Thanks.
