### ISSUE TITLE
Typo(?) in "The bottom emoji breaks rust-analyzer"

### ISSUE THREAD

**Issue by lyssieth** [fasterthanlime/feedback#180]
**Where's the problem at?**
[The article](https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer)
[A fancy highlight link to the exact issue](https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer#:~:text=actually%20provides%20completions%3A-,we%20can%20add%20it%20above,-(use%2Dpackage%20rustic))
A paragraph immediately above the issue area:
> So, now that we have emacs configured with lsp-mode and rustic, using a recent-ish rust-analyzer, we're back to square one.

**Describe the issue and a fix if you know it**
In the text immediately above the code block, you say "we can add it above `(use-package rustic)`"
But then immediately do the opposite in the code block, putting it below `(use-package rustic)`.

I may be misunderstanding how the emacs config works as I've never touched the software, but I feel like the wording is wrong?

**Comment by fasterthanlime** [comment]
Fixed, thanks!
