### ISSUE TITLE
Reading files the hard way - Part 3 (ftrace, disk layouts, ext4)

### ISSUE THREAD

**Issue by olepbr** [fasterthanlime/feedback#181]
I found something wrong on this page:

  https://fasterthanli.me/series/reading-files-the-hard-way/part-3#position=92.7

  Here's what it is:

In this code block

```rust
    // in impl Inode

    // new! this method takes an index parameter 👇
    fn data<T>(&self, sb: &Superblock, dev: T, index: u64) -> Result<Slice<T>>
    where
        T: ReadAt,
    {
        let ext_header = ExtentHeader::new(&Slice::new(&self.block, 0, Some(12)))?;
        assert_eq!(ext_header.depth, 0);
        assert!(index < ext_header.entries);

        // 👇 new: the offset depends of the index
        let offset = 12 * (index + 1);
        let ext = Extent::new(&Slice::new(&self.block, offset, Some(12)))?;
        assert_eq!(ext.len, 1);

        let offset = ext.start * sb.block_size;
        let len = ext.len * sb.block_size;
        Ok(Slice::new(dev, offset, Some(len)))
    }
```

the `assert!(index < ext_header.entries);` is also new (it previously was `assert_eq!(ext_header.entries, 1);`). Admittedly very tiny, but some readers might miss it and become confused :–)

**Comment by fasterthanlime** [comment]
> the `assert!(index < ext_header.entries);` is also new (it previously was `assert_eq!(ext_header.entries, 1);`). Admittedly very tiny, but some readers might miss it and become confused :–)

You're right! I fixed that. Thanks so much!
