### ISSUE TITLE
Typo; wrong is right in Printing ASCII cats to the terminal

### ISSUE THREAD

**Issue by kaj** [fasterthanlime/feedback#183]
**Where's the problem at?**
https://fasterthanli.me/series/building-a-rust-service-with-nix/part-3

**No, seriously, where is it?**
In the answer to Cool Bears question _Mhh quick point of order: why do we await twice?_

> Both of these can fail, so they return `Result<T, E>` where `T` is the type we get if things go right (`Response` and `String`) and `E` is the type we get if things go **right** (some error type).

**Describe the issue and a fix if you know it**
It's just a typo, the second "right" should be "wrong".

**Comment by fasterthanlime** [comment]
You're absolutely right, thanks for the report!
