### ISSUE TITLE
Using the Shipyard private crate registry with Docker

### ISSUE THREAD

**Issue by L0r3m1p5um** [fasterthanlime/feedback#184]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-7#position=33.3

  Here's what it is:

The file location mentioned here is mixed up, it should be locat/.config/cargo.toml

```
# in `locat/.config/cargo.toml`

[registries.catscii]
index = "ssh://git@ssh.shipyard.rs/catscii/crate-index.git"
```

Also, it might be worth mentioning that the password corresponding to the Gitea username is just the password we set up when creating the shipyard account. I was unclear on what credentials I was supposed to use there but that might just be me.

I also ran into an issue publishing over ssh that you didn't run into or didn't mention, but I'd guess other people might run into the same thing. I couldn't publish because ssh.shipyard.rs was not in my known hosts. I just ran 'ssh git@ssh.shipyard.rs' and accepted the host key to fix it. This was my output from 'cargo publish'.
```
note: Found `l0r3m1p5um` as only allowed registry. Publishing to it automatically.
    Updating `l0r3m1p5um` index
error: failed to update registry `l0r3m1p5um`

Caused by:
  failed to fetch `ssh://git@ssh.shipyard.rs/l0r3m1p5um/crate-index.git`

Caused by:
  error: unknown SSH host key
  The SSH host key for `ssh.shipyard.rs` is not known and cannot be validated.

  To resolve this issue, add the host key to the `net.ssh.known-hosts` array in your Cargo configuration (such as /home/ubuntu/.cargo/config.toml) or in your OpenSSH known_hosts file at /home/ubuntu/.ssh/known_hosts

  The key to add is:

  ssh.shipyard.rs ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJsY2ku5EOG2iUJVGKb4EzQVDx4zna8v+iGhd0UG8axehehGbbARKjb7sMWxLbWE07oiUJWfiNWexhOCrv0avMc=

  The ECDSA key fingerprint is: SHA256:lAawgtzO+GTfl2G8WIn9+SVvrBhnTit6+fRxqMIXgds
  This fingerprint should be validated with the server administrator that it is correct.

  See https://doc.rust-lang.org/stable/cargo/appendix/git-authentication.html#ssh-known-hosts for more information.
```

**Comment by fasterthanlime** [comment]
Thanks for the detailed report! I fixed all of these.
