### ISSUE TITLE
Generating a docker image with nix

### ISSUE THREAD

**Issue by snarkipus** [fasterthanlime/feedback#186]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-11#position=63.8

  Here's what it is:

It's entirely possible that I missed something ... just got done adding the `config.allowUnfree = true;` entry to the flake to package the geo database. It seems to build and load but the docker run command goes from:

 `docker run --rm -e SENTRY_DSN -e HONEYCOMB_API_KEY -e GEOLITE2_COUNTRY_DB -e ANALYTICS_DB -p 8080:8080 catscii:latest`

 to

 `docker run --rm -e SENTRY_DSN -e HONEYCOMB_API_KEY -p 8080:8080 catscii:latest`

Understandably, it now fails with: 
```bash
thread 'main' panicked at '$ANALYTICS_DB must be set', src/main.rs:37:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Oddly, including `-e ANALYTICS_DB` doesn't resolve it despite it being set.

```bash
snarkipus@slugz:~/catscii$ env | grep ANALYTICS_DB
ANALYTICS_DB=analytics.db
```

**Comment by fasterthanlime** [comment]
> Oddly, including `-e ANALYTICS_DB` doesn't resolve it despite it being set.

That _is_ odd. Are you tacking it on at the end or just after the last `-e` ? docker is order-sensitive like that.

**Comment by snarkipus** [comment]
> That _is_ odd. Are you tacking it on at the end or just after the last `-e` ? docker is order-sensitive like that.

```bash
snarkipus@slugz:~/catscii$ sudo docker run --rm -e SENTRY_DSN -e HONEYCOMB_API_KEY -e ANALYTICS_DB -p 8080:8080 catscii:latest
thread 'main' panicked at '$ANALYTICS_DB must be set', src/main.rs:37:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The article omits it entirely, which I'm not sure I follow either since we're still checking for its existence (and are continuing to use it?) in main.rs.

**Comment by fasterthanlime** [comment]
Oh I know what's happening in your case: it's sudo, which clears/sanitizes the environment (try "sudo env").

The docker website has instructions on how to be able to run docker as non-root.

But you're also correct that the article is missing that `-e` and I'll fix that asap.

**Comment by snarkipus** [comment]
That was it - thanks so much for the assist! Now it's breaking in exactly the way described in the next couple of paragraphs.

This has been an amazing and entertaining whirlwind tour of a staggeringly large amount of complex technology. I've had an absolute blast working through this. Thank you for what you do!
