### ISSUE TITLE
Exploring futures by going way too deep - waiting for the first one to finish

### ISSUE THREAD

**Issue by BurntNail** [fasterthanlime/feedback#188]
[From this heading, scroll down to the strace with -f](https://fasterthanli.me/articles/understanding-rust-futures-by-going-way-too-deep#it-s-waiting-for-the-first-one-to-finish)

The shell window above has a title of `shell window`, with a `$ command`, but this one has a title of `command` with no `$`.

This is mainly a consistency point - most follow the convention of the former mentioned above.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
