### ISSUE TITLE
Printing ASCII cats to the terminal

### ISSUE THREAD

**Issue by omertuc** [fasterthanlime/feedback#189]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-3#position=6.3

  Here's what it is:

![Screenshot showing that the run button icon doesn't render properly in my smartphone browser](https://user-images.githubusercontent.com/10882062/228301426-5daedbe9-5763-4add-b6c1-95d8233b5fbd.png)

Font issue on Galaxy S21+ One UI 5.1 (Android 13)

Let me know if there's further information I can provide to help troubleshoot

**Comment by fasterthanlime** [comment]
I removed the unicode character! Fixed.
