### ISSUE TITLE
"Another Article" links leading to page not found

### ISSUE THREAD

**Issue by astequ** [fasterthanlime/feedback#190]
Not really an issue on a specific article but more of a site-wide thing.

I first noticed that the link at the end of https://fasterthanli.me/series/building-a-rust-service-with-nix/part-5 linked to https://fasterthanli.me/articles/thumbhash, which is an error page.

I then I tried to follow a chain of "another article" links to see if I could catch another broken suggestion, and I found a link to https://fasterthanli.me/articles/what-makes-a-trampoline-bounce at the end of https://fasterthanli.me/articles/image-decay-as-a-service, which is also an error page.

I guess that these articles are either drafts or private ones but they probably shouldn't be suggested.

**Comment by BurntNail** [comment]
sorry for the double-report!

**Comment by fasterthanlime** [comment]
> sorry for the double-report!

No worries @BurntNail! I was indeed missing a SQL where clause to exclude drafts/future pages. I guess it never really showed up before because I didn't have a draft with the "rust" tag (that's what "Want to read another article?" selects for) for too long.
