### ISSUE TITLE
The curse of strong typing - Dead link

### ISSUE THREAD

**Issue by BurntNail** [fasterthanlime/feedback#191]
At the bottom of [TCOST](https://fasterthanli.me/articles/the-curse-of-strong-typing), there is a link to [another article](https://fasterthanli.me/articles/what-makes-a-trampoline-bounce), which goes to what I assume is your 404 page.

I guess the fix would be making the link work, or leading to a different article.

**Comment by fasterthanlime** [comment]
Duplicate of #190 (but thanks for reporting!)
