### ISSUE TITLE
What's in a Linux executable?

### ISSUE THREAD

**Issue by Takashiidobe** [fasterthanlime/feedback#193]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-1#position=25.1

  Here's what it is:
  
  On these instructions in this series:
  ```
  $ cargo new --bin elk
  $ cargo add ../delf
      Adding delf (unknown version) to dependencies
 ```
 
 `cargo add ../delf` no longer works. I'm on cargo 1.68.0.
 
 ```
$ cargo --version                                                                                
cargo 1.68.0 (115f34552 2023-02-26)
 ```
 For me, it looks like this:
 
 ```
$ cargo add ../delf
error: invalid character `.` in dependency name: `../delf`, the first character must be a Unicode XID start character (most letters or `_`)
```

Thanks for all the hard work in making these posts, I really enjoy reading through these series -- they're a good way to learn harder concepts!

**Comment by fasterthanlime** [comment]
Yeah that's one of the differences between the standalone `cargo-edit` and the one that got merged into cargo proper, iirc.

Does it work with `cargo add --path ../delf` ?

**Comment by Takashiidobe** [comment]
yep, `cargo add --path ../delf` works. It wasn't that big of a deal cause I wrote it manually in the Cargo.toml but thought I'd open an issue to preserve the error message for posterity.
