### ISSUE TITLE
Fully-released Posts RSS Feed

### ISSUE THREAD

**Issue by scolby33** [fasterthanlime/feedback#194]
Would it be possible to create an RSS feed that only includes fully-released posts? It is quite annoying to click through a post only to find that it is not out yet, and it's also annoying then to have to keep the unread post in my RSS reader for such a long time.

**Comment by fasterthanlime** [comment]
I understand why someone would want this!

However, I'm happy with how the current public RSS Feed looks.

What I'd like to do is let people generate private RSS feeds so they can read the full version from the comfort of their RSS reader. That seems like a reasonable paid feature, keeping in mind this is my full-time occupation and I'm really dependent on donations to continue.

Out of curiosity, what RSS reader are you using? I keep looking for some when testing but none of them were.. really any good.

**Comment by scolby33** [comment]
I use https://theoldreader.com/, which I switched to back when Google Reader went away _ages_ ago. I haven't really bothered to re-evaluate that decision since, but it's been doing what I need it to do.
