### ISSUE TITLE
Full-Text RSS Feed

### ISSUE THREAD

**Issue by scolby33** [fasterthanlime/feedback#195]
Would it be possible to make your RSS feed include the full text of posts so that it is not necessary to click through each one to read it?

**Comment by adezxc** [comment]
+1 for this issue

**Comment by fasterthanlime** [comment]
Not for the public RSS feed: https://github.com/fasterthanlime/feedback/issues/194#issuecomment-1995482209

(And even then, my articles are _long_, it's a LARGE payload)
