### ISSUE TITLE
Using the Shipyard private crate registry with Docker

### ISSUE THREAD

**Issue by lutzky** [fasterthanlime/feedback#197]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-7#position=0.0

  Here's what it is:

`locat/.config/cargo.toml` is mentioned twice. Should be `locat/.cargo/config.toml`. This matches https://doc.rust-lang.org/cargo/reference/config.html as well as what strace tells me cargo actually looks at.

**Comment by lutzky** [comment]
Oh, hang on, the *second* instance should probably be **`catscii`**`/.cargo/config.toml`, which is likely a separate error.

**Comment by fasterthanlime** [comment]
> Oh, hang on, the _second_ instance should probably be **`catscii`**`/.cargo/config.toml`, which is likely a separate error.

Mhhh it seems like the second instance is switching from HTTPS to SSH, I believe they're both for locat?

I think you mean the _third_ instance - I guess I didn't show that you also need to configure locat to have a registry named "catscii". Well that was a mess.

Thanks so much for reporting this, it's all fixed now!
