### ISSUE TITLE
Making a dev shell with nix flakes

### ISSUE THREAD

**Issue by Valinora** [fasterthanlime/feedback#199]
I found something wrong on this page:

  https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10#position=52.4

  Here's what it is:

  "Remember how we `said` the result of `an` import <nixpkgs> is a function that can be called with a set?"
  or
   "Remember how the result of import <nixpkgs> is a function that can be called with a set?"

**Comment by desmodrone** [comment]
thank you for the feedback!
