### ISSUE TITLE
Futures Nostalgia — Missing “tired of reading video”

### ISSUE THREAD

**Issue by Malien** [fasterthanlime/feedback#202]
I found something wrong on this page:

  https://fasterthanli.me/articles/futures-nostalgia#position=58.2

  Here's what it is:
From one of your previous vids, you’ve made the whole video suggestion thingy. I’ve just encountered a yellow box, with the video player missing. Not sure this was reported before. 
![0905400E-4B8D-451F-8BA1-EC833336B105](https://user-images.githubusercontent.com/7205038/233019170-531d99df-80cd-415c-929a-b4e56024d1c3.jpeg)

I’m on iOS 14.7 Safari

**Comment by fasterthanlime** [comment]
Well I'm not sure what's going on there. I'll have to reproduce on an iPhone! I'm getting one soon :) Ping me in a week if I haven't gotten to this?

**Comment by fasterthanlime** [comment]
/remind me in a week to check this

**Comment by Malien** [comment]
Hi, Amos. Nice to hear from you. Hope you are doing fine. 

I wasn't able to reproduce the issue on a iOS 16.1, so it seems that somewhere in-between the safari bug was fixed. 

UPD: Just figured it out. iOS 14.7 Safari doesn't support css `aspect-ratio` property on the `.youtube-embed` element. The video embed is there, just with the height of 0. 

I am in minority here tho, with just [~1.54% of iOS users](https://caniuse.com/mdn-css_properties_aspect-ratio) that do not have support of `aspect-ratio`. (and ~9% of all users if you count things like IE and such). 

Overall the degradation is somewhat graceful. Not like the site becomes unusable, or the layout is impacted in any significant way. You might use the 'ol `padding-bottom: 17%` hack, or just 
```css
@supports not (aspect-ratio: 16/9) {
  .youtube-embed {
    display: none
  }
}
```
Or just leave it as is. Not that many users are going to experience it.

_Is it because of people like me, sticking to the old devices, that we can't have nice things? 🤔_

**Comment by fasterthanlime** [comment]
> UPD: Just figured it out. iOS 14.7 Safari doesn't support css `aspect-ratio` property on the `.youtube-embed` element. The video embed is there, just with the height of 0.

Ohhhh wowowow. Old Safari is the Old New IE6 for real (they've picked up the pace since, afaict). Thanks for the workaround, I've simply hidden the embed for old browsers.

**Comment by Malien** [comment]
@fasterthanlime, I think I've (and as an extension you) made a mistake in that snippet. It's not the `.youtube-embed` element (just a player) that should be hidden. It's the `.youtube-promo` one (the whole yellow "Tired of reading?" block).

**Comment by fasterthanlime** [comment]
Woops yes, nice catch! Fixed!
