### ISSUE TITLE
Futures Nostalgia — small little typo

### ISSUE THREAD

**Issue by Malien** [fasterthanlime/feedback#203]
I found something wrong on this page:

  https://fasterthanli.me/articles/futures-nostalgia#position=60.2

  Here's what it is:
In the section “Accepting Connections”, the paragraph:

> But in some of the tests, we want to simulate a service that's... up, but not quite up. Like, it has reserved a port (so another service can't bind to it, not without some naughty socket flags we're not using there), but it hasn't started listening for connections yet, so any connection attempts will be met with a RST packet, **with** is TCP for: "we see what you're going for but nah": on the client side, we'd see something like "connection refused".

I think you’ve meant “which”, not “with”

**Comment by Malien** [comment]
Also, in the same section, paragraph:

> So... what I'm getting at is that, if we want that behavior (bind, wait a couple seconds, then listen) with a hyper server, and we haven't realized we could simply wait to build the server, then we can't use `AddrIncoming`: we need to **use implement** the [Accept](https://docs.rs/hyper/latest/hyper/server/accept/trait.Accept.html) trait ourselves.

I think you’ve meant to say either “use the Accept trait” or “implement the Accept trait”, not “use implement the Accept teait”

**Comment by desmodrone** [comment]
both fixed thank you!
