### ISSUE TITLE
I'm in ur address space

### ISSUE THREAD

**Issue by aldreth** [fasterthanlime/feedback#22]
I found something wrong on this page:

https://fasterthanli.me/videos/im-in-ur-address-space#position=0.0

Here's what it is:

The video doesn't play when using Firefox Beta on Android

Firefox Beta:
100.0.0-beta.7 (Build #2015876107), d6a6b0a29+
AC: 100.0.8, 6d78625ccc
GV: 100.0-20220421201645
AS: 91.1.1

Android 12 - kernel 5.10.66-android12-9-00001-g51e133b6e4eb-ab8103786
#1 Fri Jan 21 06:54:49 UTC 2022

Google pixel 6

The video works in Chrome on the same phone

**Comment by fasterthanlime** [comment]
I've retired my video platform for the time being, so I'll close this.
