### ISSUE TITLE
Sum read time for entire series.

### ISSUE THREAD

**Issue by Dygear** [fasterthanlime/feedback#48]
Please could you add to the series overview page the total read time as sum of the read time across all of the contained articles? Such as `A series of {numberOfArticles} · {sumedReadTime} minute read`.

Thank you.

P.S. Love the site. I've been reading the content over the last few days as I've tried to get a stronger grasp for Rust. Your writing style is very helpful to the way that I learn.

**Comment by fasterthanlime** [comment]
I apparently did that on May 10, but forgot to close this!

<img width="724" alt="image" src="https://user-images.githubusercontent.com/7998310/224512535-ed97dc50-ba8f-4d74-85dd-f36aab168a76.png">
