### ISSUE TITLE
The simplest shared library

### ISSUE THREAD

**Issue by bdolgov** [fasterthanlime/feedback#56]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-5#position=14.0

  Here's what it is:

The latest example says:

```
$ PATH=".:$PATH" ./hello-pie
```

But it was supposed to illustrate that adding `.` to `$PATH` allows not prefixing the command with `./`. Probably, it should be:

```
$ PATH=".:$PATH" hello-pie
```

**Comment by fasterthanlime** [comment]
You're absolutely correct. Fixed.
