### ISSUE TITLE
Text Processing in Rust - You are the man for the job!

### ISSUE THREAD

**Issue by joaocarvalhoopen** [fasterthanlime/feedback#60]
Hello Amos,

I have something to tell you :-)

Text Processing is one of the 3 cores competences of programming. Jointly with binary processing and numeric processing.

As you know, Text Processing is not easy!

Currently the Rust community is severely under served in regarding to learning materials on, how to do Text Processing in Rust.

You have previously made a excellent article on the beginnings of the subject:

**Working with strings in Rust** - fasterThanLime Blog
 [https://fasterthanli.me/articles/working-with-strings-in-rust](https://fasterthanli.me/articles/working-with-strings-in-rust)

do it like a sequence of articles, if it's better for you then a mdbook. But give that to the community, because the community is needing of better info, on how to do Text Processing in Rust.
The beginner and the intermediate rust developer will forever tank you! 

I previously, have made a call for it to the community in here:

**Please make a mdbook on Text Processing in Rust**
[https://users.rust-lang.org/t/please-make-a-mdbook-on-text-processing-in-rust](https://users.rust-lang.org/t/please-make-a-mdbook-on-text-processing-in-rust)

You are the man for job!

Please consider accepting this important challenge.

In it, the community told me to do it myself, but I'm not currently knowledgeable enough to do a good job on it. You will do a much better job.

In Rust, the only writing that I have made is my guide:

**How to learn modern Rust** - joaocarvalhoopen
[https://github.com/joaocarvalhoopen/How_to_learn_modern_Rust](https://github.com/joaocarvalhoopen/How_to_learn_modern_Rust)

Thank you,

The very best regards,
João

**Comment by fasterthanlime** [comment]
Hey João, I have several projects in the works and am not taking requests via this issue tracker. I'm sure you'll do a fine job if you do it! We do need more folks writing, it can't all be me :)
