### ISSUE TITLE
Windows dynamic libraries, calling conventions, and transmute

### ISSUE THREAD

**Issue by pawlos** [fasterthanlime/feedback#61]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-ping/part-2#position=79.7

  Here's what it is:

- in the example code "MessageBox\0" is passed to `LoadLibrary`, where in fact it should be "MessageBoxA\0". I the later code samples, "MessageBoxA\0" is correctly used.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
