### ISSUE TITLE
Persist dark/light theme choice for logged-out users via cookie?

### ISSUE THREAD

**Issue by Bassetts** [fasterthanlime/feedback#62]
The manual theme switcher is more forgetful than me when I walk into a room and suddenly wonder why I decided to come here in the first place. It would be nice if it remembered my selection so I didn't burn my retinas on every page navigation when wandering around the site late at night when I really should be sleeping.

Side note: I have resist fingerprinting enabled in Firefox which is why `prefers-color-scheme: dark` doesn't work for me and default to the dark them in the first place.

**Comment by fasterthanlime** [comment]
This probably involves setting a cookie, since rendering happens server-side.

Does your privacy-conscious setup even allow setting cookies? If not, I don't see a fix for that.

**Comment by Bassetts** [comment]
By default cookies are blocked but I override it on a per-site basis.

**Comment by fasterthanlime** [comment]
In Firefox 123.0.1, I tested with Strict Enhanced Tracking Protection:

<img width="1409" alt="image" src="https://github.com/fasterthanlime/feedback/assets/7998310/37b943ad-2862-4d7d-8e02-db415c68c383">

And it shows the dark mode properly:

<img width="1409" alt="image" src="https://github.com/fasterthanlime/feedback/assets/7998310/4c6b8eea-e652-4c87-9a2a-3d02578fbe36">
