### ISSUE TITLE
Not about: I want off Mr. Golang's Wild Ride

### ISSUE THREAD

**Issue by cgay** [fasterthanlime/feedback#64]
I found something great on this page:

  https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride

  Here's what it is: I learned a lot. Thanks.

I do have an ulterior motive for filing this issue though:  Would you mind pointing me at what software you use to write the blog, and what theme you use?  I've been looking around for something

* simple
* readable
* that displays code really well

and your blog seems to have all these properties, plus a nice dark/light mode switcher.

Thanks.
-Carl

**Comment by fasterthanlime** [comment]
Hey Carl, unfortunately it's all custom! https://fasterthanli.me/articles/a-new-website-for-2020

**Comment by cgay** [comment]
ok, thanks for letting me know.
