### ISSUE TITLE
Missing syntax highlighting 

### ISSUE THREAD

**Issue by Sciencentistguy** [fasterthanlime/feedback#65]
**Where's the problem at?**
https://fasterthanli.me/series/making-our-own-executable-packer/part-2

**No, seriously, where is it?**
![Screenshot_20220530-005638_Firefox.jpg](https://user-images.githubusercontent.com/4983935/170896626-142c9cc6-380a-4e9f-b125-39288ad5a04a.jpg)

(about 1/4 the way through, ish) 

**Describe the issue and a fix if you know it**
This code block is probably not tagged with a language, so it's not highlighted.

**Comment by fasterthanlime** [comment]
Fixed, thanks for the report!
