### ISSUE TITLE
s/seemless/seamless in "The curse of strong typing"

### ISSUE THREAD

**Issue by ErichDonGubler** [fasterthanlime/feedback#70]
**Where's the problem at?**

https://fasterthanli.me/articles/the-curse-of-strong-typing

**No, seriously, where is it?**

Emphasis mine:

> In Python, you have floats, and integers. Python 3 handles bigints **seemlessly**: doing arithmetic on small integer values is still "cheap".

**Describe the issue and a fix if you know it**

"seemlessly" is a misspelling of ["seamlessly"](https://www.merriam-webster.com/dictionary/seamless).

**Comment by fasterthanlime** [comment]
Fixed, thanks!
