### ISSUE TITLE
Dynamic linker speed and correctness: unrendered shortcode

### ISSUE THREAD

**Issue by Sciencentistguy** [fasterthanlime/feedback#76]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-8#position=78.7

  Here's what it is:

An unrendered shortcode about 70% of the way down:
```
{% sc tip %} One really ought to make measurements before making claims like that.

And then not make the claims anyway, because measurements lie all the time. {% endsc %}
```
![image](https://user-images.githubusercontent.com/4983935/173048129-5f7eedd0-ccdf-4ec6-a40c-dfababb927a0.png)

**Comment by fasterthanlime** [comment]
Fixed today by accident, thanks!
