### ISSUE TITLE
Thread-local storage: Garbled text

### ISSUE THREAD

**Issue by Sciencentistguy** [fasterthanlime/feedback#78]
I found something wrong on this page:

  https://fasterthanli.me/series/making-our-own-executable-packer/part-13#position=25.4

  Here's what it is:

![image](https://user-images.githubusercontent.com/4983935/173255990-1acde2c2-16a6-411c-b1c7-f100fc5a95d4.png)

**Comment by fasterthanlime** [comment]
Finally figured out why it was doing that!

Here's how it's supposed to look:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/7998310/224513359-b474f734-1cc0-4f73-86bf-0b6085276500.png">

...in all its KaTeX glory. Thanks for the report!
