### ISSUE TITLE
KaTeX error in code block (AOC 2020 Day 14)

### ISSUE THREAD

**Issue by ericfinger** [fasterthanlime/feedback#80]
https://fasterthanli.me/series/advent-of-code-2020/part-14

Near the beginning, just below the bit-mask explanation a code block reads:
``KaTeX error (block): failed to execute js (detail: undefined not callable (property 'fill' of [object Array]): JavaScript runtime error (TypeError))``

**Comment by fasterthanlime** [comment]
Does this look alright now? Here's what I see:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/7998310/224513440-68937025-ad2f-477c-b088-8efa632ed1d1.png">
