### ISSUE TITLE
When rustc explodes: see -> seen

### ISSUE THREAD

**Issue by olepbr** [fasterthanlime/feedback#83]
I found something wrong on this page:

  https://fasterthanli.me/articles/when-rustc-explodes#position=55.2

Here's what it is:

"Yeah yeah, I've see the perf patch for that [...]" should really be "Yeah yeah, I've _seen_ the perf patch for that [...]"

Thanks for another great article :–)

**Comment by fasterthanlime** [comment]
Thanks!
