### ISSUE TITLE
When rustc explodes - typo in the 'rust/compiler/rustc_trait_selection/src/traits/select/mod.rs' path

### ISSUE THREAD

**Issue by dmitris** [fasterthanlime/feedback#84]
I found something wrong on this page:

  https://fasterthanli.me/articles/when-rustc-explodes#position=92.3

  Here's what it is:

comment in code after "Anyway, if we do a quick search in rustc's code, we find this function:"

//  in `rust/compiler/rustc_trait_selection/traits/select/mod.rs`

should be

//  in `rust/compiler/rustc_trait_selection/src/traits/select/mod.rs`

(missing 'src/') - https://github.com/rust-lang/rust/blob/master/compiler/rustc_trait_selection/src/traits/select/mod.rs#L439

Also the same in the next code block.

**Comment by fasterthanlime** [comment]
Fixed, thanks!
