### ISSUE TITLE
Proc macro article: "from from"

### ISSUE THREAD

**Issue by Walther** [fasterthanlime/feedback#89]
**Where's the problem at?**
https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions

**No, seriously, where is it?**
> Luckily rust-analyzer already needs to run `cargo check` for other reasons (because most diagnostics **from from** it, rather than rust-analyzer itself). That has the nice side-effect of compiling all proc macros to dylibs, as we've seen.

**Describe the issue and a fix if you know it**
> ... most diagnostics come from it ...

**Comment by LDVSOFT** [comment]
I guess the idea was to use _form from_.
