### ISSUE TITLE
Typo in Proc macro support in rust-analyzer for nightly rustc versions

### ISSUE THREAD

**Issue by mendelsimon** [fasterthanlime/feedback#93]
**Where's the problem at?**
https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions

**No, seriously, where is it?**
> All crates are actually compileD:

**Describe the issue and a fix if you know it**
The final "D" in "compileD" should be lowercase: 
> All crates are actually compiled:

**Comment by fasterthanlime** [comment]
Fixed earlier, thanks
