### ISSUE TITLE
Typos in Article

### ISSUE THREAD

**Issue by rj-jones** [fasterthanlime/feedback#95]
**Where's the problem at?**
https://fasterthanli.me/series/making-our-own-ping/part-1

**No, seriously, where is it?**
Eventually, those the line between those two use cases blurred, as a standard protocol for remotely control computers emerged, [Telnet](https://en.wikipedia.org/wiki/Telnet).

**Describe the issue and a fix if you know it**
Eventually, the line between was blurred, as a standard protocol for remotely controlling computers emerged, [Telnet](https://en.wikipedia.org/wiki/Telnet).

**Comment by fasterthanlime** [comment]
Fixed, thanks!
