### ISSUE TITLE
Pressing page down scrolls past text on Firefox

### ISSUE THREAD

**Issue by nortti0** [fasterthanlime/feedback#96]
I found something wrong on this page:

  https://fasterthanli.me/*

  Here's what it is:

If you press Page Down when at the top of any page on the website, about one body-text-line worth of content gets skipped over (hidden under the popover topbar). This does not happen if you have already scrolled down the page by any amount.

Upon page load:
![Screenshot 2022-08-03 at 18-43-00 Declarative memory management](https://user-images.githubusercontent.com/66438552/182651354-a9d4bc0f-a5ce-494a-93ae-f8a950404b20.png)

After pressing Page Down once:
![Screenshot 2022-08-03 at 18-43-10 Declarative memory management](https://user-images.githubusercontent.com/66438552/182651373-7eb6e720-5aa6-43ff-aef9-6227cdf53c89.png)

I am using Firefox 103.0 under Linux.

**Comment by fasterthanlime** [comment]
I'm not aware of any way to fix this (with CSS for example), short of completely changing how the top bar works. Hiding it on scroll down (and showing it again on scroll up) could be an option, some websites do that, but idk how I feel about it.

**Comment by fasterthanlime** [comment]
Looked at this again and I noticed it's not happening on Chrome on Windows.

Before Scroll down:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/7998310/224512484-8dc931fe-7f34-44ce-8349-d30797abe084.png">


After:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/7998310/224512481-8e4bca98-7cce-455d-ab8a-b17628aa22a4.png">

**Comment by nortti0** [comment]
Can verify it doesn't get skipped with Chrome on Linux either. Which is interesting, since otherwise it seems to scroll about as much as Firefox does. Could it possibly process the popover topbar appearing and scroll calculation in different order than Firefox? (I don't know the specifics of how you implement the bar)

**Comment by fasterthanlime** [comment]
> Can verify it doesn't get skipped with Chrome on Linux either

I actually remembered today why it's supposed to work: there's a CSS rule on `html { ... }` that tells the browser how to scroll:

```css
html {
  scroll-padding-top: 85px;
}
```

cf. https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top

**Comment by fasterthanlime** [comment]
Firefox 123 seems to be behaving correctly for me on macOS now.

Before hitting page-down (or space):

<img width="1409" alt="image" src="https://github.com/fasterthanlime/feedback/assets/7998310/b7eda3a2-5088-4d48-a8ab-2b2896c636f4">

After:

<img width="1409" alt="image" src="https://github.com/fasterthanlime/feedback/assets/7998310/a201acc8-b79d-482f-b45e-661bf00079a5">
