### ISSUE TITLE
Markdown version of articles

### ISSUE THREAD

**Issue by HKalbasi** [fasterthanlime/feedback#97]
Sorry if here is wrong place.

I want to present rust somewhere, and for that I want to make a jupyter notebook out of your great post [A half-hour to learn Rust](https://fasterthanli.me/articles/a-half-hour-to-learn-rust) and run it step by step at the presentation. But copying each cell manually is hard. Assuming that you write articles in markdown (or similar formats which can be converted to markdown), would you mind to public them somewhere? With that I can build a jupyter notebook via `jupytext` and save some manual work.

**Comment by fasterthanlime** [comment]
I don't have a way to do this that doesn't create a lot of extra work for me at the moment - the source _is_ markdown, but I also have time-gated content, and the markdown has extra markup that other processors might not understand (shortcodes, katex etc.)
